import { randomUUID } from 'node:crypto';
import { describe, expect, it } from 'vitest';
import { applyEvent, canPriceSearch, dates, defaultCriteria, initialState, missingSearchDetails, visibleCriteria, withSuitability, type DomainEvent, type Quote } from '../src/lib/domain';
const at = '2026-09-26T12:00:00.000Z';
function event(type: string, payload: Record<string, unknown>, revision = 0): DomainEvent { return { id: randomUUID(), tripId: randomUUID(), type, payload, revision, occurredAt: at }; }
describe('unknown trip intake', () => {
  it('starts without presenting internal fallback values as user choices', () => { const state = initialState(); expect(state.confirmedCriteria).toEqual([]); expect(Object.values(visibleCriteria(state)).every(value => value === null)).toBe(true); expect(missingSearchDetails(state)).toEqual(['origin','travellers','nights','dates','budget']); expect(canPriceSearch(state)).toBe(false); });
  it('only exposes preferences actually saved in the workspace', () => { const state = initialState({ noCar: true, interests: ['food'], stayStyle: 'Private room', notes: [] }); expect(visibleCriteria(state)).toMatchObject({ noCar: true, interests: ['food'], stayStyle: 'Private room', budget: null, origin: null, travellers: null, region: null }); expect(canPriceSearch(state)).toBe(false); });
  it('supports discovery intent without assuming budget, origin or dates', () => { const state = applyEvent(initialState(), event('trip_patch', { region: 'Jamaica', interests: ['beaches'] })); expect(visibleCriteria(state)).toMatchObject({ region: 'Jamaica', budget: null, origin: null, travellers: null, departureStart: null }); expect(canPriceSearch(state)).toBe(false); });
  it('confirms an explicit value even when it equals an internal fallback', () => { const state = applyEvent(initialState(), event('trip_patch', { budget: 1000, currency: 'GBP' })); expect(state.revision).toBe(1); expect(visibleCriteria(state).budget).toBe(1000); expect(state.confirmedCriteria).toEqual(['budget','currency']); expect(missingSearchDetails(state)).not.toContain('budget'); });
  it('does not confirm logistics merely because a question was answered', () => { let state = applyEvent(initialState(), event('question', { id: 'budget', prompt: 'What is your budget?', options: ['£1,000','£2,000'] })); state = applyEvent(state, event('question_answered', { id: 'budget', answer: '£2,000' })); expect(visibleCriteria(state).budget).toBeNull(); expect(state.questions[0].answer).toBe('£2,000'); });
  it('allows cost searches only once all required search inputs are explicitly set', () => { const state = applyEvent(initialState(), event('trip_patch', { ...defaultCriteria })); expect(canPriceSearch(state)).toBe(true); for (const key of ['origin','originCode','travellers','nights','budget','currency','departureStart'] as const) expect(canPriceSearch({ ...state, confirmedCriteria: state.confirmedCriteria!.filter(confirmed => confirmed !== key) })).toBe(false); });
  it('accepts a fixed departure outside the hidden fallback window without confirming that window', () => { const state = applyEvent(initialState(), event('trip_patch', { departureDate: '2027-05-10' })); expect(visibleCriteria(state)).toMatchObject({ departureDate: '2027-05-10', departureStart: null, departureEnd: null }); expect(missingSearchDetails(state)).not.toContain('dates'); });
  it('accepts partial future windows without comparing them against hidden October dates', () => { let state = applyEvent(initialState(), event('trip_patch', { departureStart: '2027-05-10' })); expect(missingSearchDetails(state)).toContain('dates'); expect(visibleCriteria(state).departureEnd).toBeNull(); state = applyEvent(state, event('trip_patch', { departureEnd: '2027-05-20' }, state.revision)); expect(missingSearchDetails(state)).not.toContain('dates'); });
  it('rejects price results until intake is complete even when fallback dates and party happen to match', () => { let state = initialState(); state = applyEvent(state, event('candidate', { id: 'jamaica', name: 'Jamaica', country: 'Jamaica', airport: 'MBJ', image: '', summary: 'Checking beaches', highlights: [], sources: [], status: 'researching' })); const quote: Quote = { total: 200, currency: 'GBP', travellers: 2, ...dates(state.criteria), checkedAt: at, url: 'https://example.com/fare', label: 'Return fare', scope: 'return-flights', includes: 'Two people', provider: 'Fixture' }; state = applyEvent(state, event('quote', { candidateId: 'jamaica', kind: 'flights', quote })); expect(state.candidates[0].flight).toBeUndefined(); });
  it('does not infer confirmations from an old snapshot or erase its conversation history', () => { const state = initialState(); delete state.confirmedCriteria; state.messages.push({ id: 'old-message', role: 'user', text: 'I want to go to Jamaica.', at }); state.phase = 'ready'; const restored = withSuitability(state); expect(restored.messages).toEqual(state.messages); expect(restored.confirmedCriteria).toEqual([]); expect(visibleCriteria(restored).budget).toBeNull(); expect(restored.phase).not.toBe('ready'); });
  it('does not expose assumed dates or party in a candidate summary before intake', () => { const state = initialState(); state.candidates.push({ id: 'jamaica', name: 'Jamaica', country: 'Jamaica', airport: 'MBJ', image: '', summary: '10–15 October for two people', highlights: [], sources: [], status: 'researching' }); const next = applyEvent(state, event('trip_patch', { interests: ['beaches'] })); expect(next.candidates[0].summary).not.toContain('October'); expect(next.candidates[0].summary).not.toContain('two'); expect(next.candidates[0].summary).toContain('Waiting for your trip details'); });
});
